server:
  tomcat: 
    uri-encoding: UTF-8
  max-http-header-size: 4048576
spring: 
  aop:
    proxy-target-class: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10Mb
      max-request-size: 10Mb
      
# shiro登录失效时间      
shiro:
  session:
    timeout: 3600000
    
hefa-user-service: 
  ribbon:
    ConnectTimeout: 6000
    ReadTimeout: 6000
    OkToRetryOnAllOperations: false
    MaxAutoRetriesNextServer: 0
    MaxAutoRetries: 0 
hefa-order-service:
  ribbon:
    ConnectTimeout: 6000
    ReadTimeout: 6000
    OkToRetryOnAllOperations: false
    MaxAutoRetriesNextServer: 0
    MaxAutoRetries: 0 