server:
  tomcat: 
    uri-encoding: UTF-8
  max-http-header-size: 4048576
spring: 
  aop:
    proxy-target-class: true
  http:
    multipart:
      maxFileSize: 100Mb
      maxRequestSize: 100Mb
eureka:
  client:
    service-url:
       defaultZone: http://root:123456@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${spring.application.name}:${spring.application.instance_id:${server.port}}
      
feign:
  httpclient: 
    enabled: true #feign原生是调用java.url 去发起HTTP请求，此配置是将请求客户端更换成apahce http
  hystrix: 
    enabled: false
