server:
  tomcat: 
    uri-encoding: UTF-8
  max-http-header-size: 4048576
spring: 
  redis:
    database: 0
    #host: 192.168.1.222
    host: 120.78.162.226
    port: 6379
    #password: AgPaYRedis6
  aop:
    proxy-target-class: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10Mb
      max-request-size: 10Mb
hefa-user-service: 
  ribbon:
    ConnectTimeout: 6000
    ReadTimeout: 6000
    OkToRetryOnAllOperations: false
    MaxAutoRetriesNextServer: 0
    MaxAutoRetries: 0 

